[[actions]]
name = "play"
platform = "windows"
path = "AnjusHighRes/AnjusHighRes.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "AnjusHighRes/AnjusHighRes"
args = ["--launched-through-itch"]
